import { describe, it, expect } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpDir } from './helpers.js';

function run(args: string[], cwd?: string) {
  const r = spawnSync('npx', ['tsx', join(process.cwd(), 'src/cli.ts'), ...args], {
    encoding: 'utf8', cwd: cwd ?? process.cwd(),
  });
  return { code: r.status, out: r.stdout + r.stderr };
}

describe('vault CLI end to end', () => {
  it('init to project to add to compile', () => {
    const vault = join(tmpDir(), 'v');
    const work = tmpDir();

    expect(run(['init', vault]).code).toBe(0);
    expect(run(['--vault', vault, 'project', 'new', 'Demo', '--root', work]).code).toBe(0);

    const add = run(['--vault', vault, 'add', 'fact', 'Deploy on Vercel', '-b', 'branch main'], work);
    expect(add.code).toBe(0);
    expect(add.out).toMatch(/fct-/);

    const compile = run(['--vault', vault, 'compile'], work);
    expect(compile.code).toBe(0);
    for (const f of ['CLAUDE.md', 'AGENTS.md', '.cursorrules']) {
      const content = readFileSync(join(work, f), 'utf8');
      expect(content).toContain('GENERATED');
      expect(content).toContain('Deploy on Vercel');
    }
  });

  it('never overwrites a hand-written CLAUDE.md, unless forced', () => {
    const vault = join(tmpDir(), 'v');
    const work = tmpDir();
    run(['init', vault]);
    run(['--vault', vault, 'project', 'new', 'Demo', '--root', work]);
    writeFileSync(join(work, 'CLAUDE.md'), '# My precious hand-written instructions\n');
    const r = run(['--vault', vault, 'compile', '--tool', 'claude'], work);
    expect(r.code).toBe(0);
    expect(r.out).toMatch(/skipped .*CLAUDE\.md/);
    expect(readFileSync(join(work, 'CLAUDE.md'), 'utf8')).toContain('precious hand-written');
    const forced = run(['--vault', vault, 'compile', '--tool', 'claude', '--force'], work);
    expect(forced.out).toMatch(/wrote .*CLAUDE\.md/);
    expect(readFileSync(join(work, 'CLAUDE.md'), 'utf8')).toContain('GENERATED by vault');
    // and a generated file is always ours to regenerate without --force
    const again = run(['--vault', vault, 'compile', '--tool', 'claude'], work);
    expect(again.out).toMatch(/wrote .*CLAUDE\.md/);
  });

  it('compiled files teach the model about the MCP channel', () => {
    const vault = join(tmpDir(), 'v');
    const work = tmpDir();
    run(['init', vault]);
    run(['--vault', vault, 'project', 'new', 'Demo', '--root', work]);
    run(['--vault', vault, 'compile'], work);
    expect(readFileSync(join(work, 'CLAUDE.md'), 'utf8')).toContain('call get_context');
  });

  it('mine --from-now fast-forwards offsets without extracting', () => {
    const vault = join(tmpDir(), 'v');
    const root = tmpDir();
    run(['init', vault]);
    mkdirSync(join(root, '-Users-x-proj'), { recursive: true });
    const t = join(root, '-Users-x-proj', 's.jsonl');
    writeFileSync(t, JSON.stringify({ type: 'user', cwd: '/x', message: { role: 'user', content: 'old history' } }) + '\n');
    const r = run(['--vault', vault, 'mine', '--from-now', '--root', root]);
    expect(r.code).toBe(0);
    expect(r.out).toMatch(/fast-forwarded 1 transcripts/);
    const offsets = JSON.parse(readFileSync(join(vault, '.mine', 'offsets.json'), 'utf8'));
    expect(offsets[t]).toBeGreaterThan(0);
  });

  it('rejects unknown record type with guidance', () => {
    const vault = join(tmpDir(), 'v');
    run(['init', vault]);
    run(['--vault', vault, 'project', 'new', 'Demo']);
    const r = run(['--vault', vault, 'add', 'state', 'x', '-p', 'demo']);
    expect(r.code).toBe(1);
    expect(r.out).toMatch(/vault state/);
  });

  it('stores relative --root as an absolute path so later cwds cannot misattribute records', () => {
    const vault = join(tmpDir(), 'v');
    const projA = tmpDir();
    const projB = tmpDir();
    run(['init', vault]);
    // register both projects with a RELATIVE root from inside their own dirs
    expect(run(['--vault', vault, 'project', 'new', 'ProjA', '--root', '.'], projA).code).toBe(0);
    expect(run(['--vault', vault, 'project', 'new', 'ProjB', '--root', '.'], projB).code).toBe(0);
    // adding from projB without -p must land in ProjB, never ProjA
    const add = run(['--vault', vault, 'add', 'fact', 'marker-in-B'], projB);
    expect(add.code).toBe(0);
    const list = run(['--vault', vault, 'list', '-p', 'projb']);
    expect(list.out).toContain('marker-in-B');
    expect(run(['--vault', vault, 'list', '-p', 'proja']).out).not.toContain('marker-in-B');
  });

  it('rejects an unknown --kind with guidance', () => {
    const vault = join(tmpDir(), 'v');
    run(['init', vault]);
    const r = run(['--vault', vault, 'project', 'new', 'Demo', '--kind', 'banana']);
    expect(r.code).toBe(1);
    expect(r.out).toMatch(/code \| creative/);
  });

  it('rejects a non-numeric --budget with guidance', () => {
    const vault = join(tmpDir(), 'v');
    const work = tmpDir();
    run(['init', vault]);
    run(['--vault', vault, 'project', 'new', 'Demo', '--root', work]);
    const r = run(['--vault', vault, 'compile', '--budget', 'abc'], work);
    expect(r.code).toBe(1);
    expect(r.out).toMatch(/Invalid --budget/);
  });

  it('prints a clean one-line error, not a stack trace, on init over an existing vault', () => {
    const vault = join(tmpDir(), 'v');
    run(['init', vault]);
    const r = run(['init', vault]);
    expect(r.code).toBe(1);
    expect(r.out).toMatch(/already exists/i);
    expect(r.out).not.toMatch(/at .*cli\.ts/);
  });

  it('compile --all compiles every project with an existing path root, skipping projects without one', () => {
    const vault = join(tmpDir(), 'v');
    const rootA = tmpDir();
    const rootB = tmpDir();
    run(['init', vault]);
    run(['--vault', vault, 'project', 'new', 'ProjA', '--root', rootA]);
    run(['--vault', vault, 'project', 'new', 'ProjB', '--root', rootB]);
    // no --root: this project has no path root at all, so --all must skip it silently
    run(['--vault', vault, 'project', 'new', 'ProjC']);

    const r = run(['--vault', vault, 'compile', '--all', '--tool', 'claude']);
    expect(r.code).toBe(0);
    expect(existsSync(join(rootA, 'CLAUDE.md'))).toBe(true);
    expect(existsSync(join(rootB, 'CLAUDE.md'))).toBe(true);
    expect(r.out).toMatch(/compiled 2 projects, skipped 0 files/);

    const conflict = run(['--vault', vault, 'compile', '--all', '--project', 'x']);
    expect(conflict.code).toBe(1);
  });
});
