import type { Adapter } from './index.js';
import { MCP_HINT, renderMarkdownBody } from './index.js';

// .cursorrules is plain text; markdown reads fine there, but use a text header
export const cursor: Adapter = {
  name: 'cursor',
  filename: '.cursorrules',
  render: (ctx) => `# GENERATED by vault - do not edit. Regenerate with \`vault compile\`.\n\n${renderMarkdownBody(ctx)}\n${MCP_HINT}\n`,
};
