import type { CompiledContext } from '../types.js';
import { claude } from './claude.js';
import { agents } from './agents.js';
import { cursor } from './cursor.js';

export interface Adapter {
  name: string;
  filename: string;
  render(ctx: CompiledContext): string;
}

export const adapters: Record<string, Adapter> = { claude, agents, cursor };

export function getAdapter(name: string): Adapter {
  const a = adapters[name];
  if (!a) throw new Error(`Unknown adapter "${name}". Available: ${Object.keys(adapters).join(', ')}`);
  return a;
}

export const GENERATED_HEADER =
  '<!-- GENERATED by vault - do not edit. Regenerate with `vault compile`. -->';

/** shared section layout for markdown-based targets */
export function renderMarkdownBody(ctx: CompiledContext): string {
  const parts: string[] = [];
  parts.push(ctx.project.facts);
  if (ctx.state) parts.push(`## State (work in progress)\n\n${ctx.state}`);
  const taste = [...ctx.globalTaste, ...ctx.records.taste];
  if (taste.length) parts.push(`## Taste & style\n\n${taste.join('\n')}`);
  if (ctx.records.recipe.length) parts.push(`## Recipes (how things are done here)\n\n${ctx.records.recipe.join('\n')}`);
  if (ctx.records.decision.length) parts.push(`## Decisions\n\n${ctx.records.decision.join('\n')}`);
  if (ctx.records.fact.length) parts.push(`## Facts\n\n${ctx.records.fact.join('\n')}`);
  if (ctx.unconfirmed.length) parts.push(`## Recent (unconfirmed, take with a grain of salt)\n\n${ctx.unconfirmed.join('\n')}`);
  if (ctx.profile) parts.push(`## About the user\n\n${ctx.profile}`);
  if (ctx.droppedCount > 0) parts.push(`<!-- ${ctx.droppedCount} records omitted by token budget; full detail lives in the vault -->`);
  return parts.join('\n\n') + '\n';
}
