import type { CompiledContext } from '../types.js';
import { claude } from './claude.js';
import { agents } from './agents.js';
import { cursor } from './cursor.js';
import { gemini } from './gemini.js';
import { windsurf } from './windsurf.js';

export interface Adapter {
  name: string;
  filename: string;
  render(ctx: CompiledContext): string;
}

export const adapters: Record<string, Adapter> = { claude, agents, cursor, gemini, windsurf };

export function getAdapter(name: string): Adapter {
  const a = adapters[name];
  if (!a) throw new Error(`Unknown adapter "${name}". Available: ${Object.keys(adapters).join(', ')}`);
  return a;
}

/** which compiled-file adapter each detected AI tool uses (setup wizard, spec §11) */
export const TOOL_ADAPTERS: Record<string, string> = {
  'claude-code': 'claude',
  'claude-desktop': 'claude',
  codex: 'agents',
  cursor: 'cursor',
  gemini: 'gemini',
  windsurf: 'windsurf',
};

export const GENERATED_HEADER =
  '<!-- GENERATED by clankervault - do not edit. Regenerate with `clanker compile`. -->';

/**
 * Markers that identify a file as ours to overwrite: the current marker, plus the
 * pre-rename marker still sitting in files a `vault`-era install already generated
 * on disk. Both must be honored so existing compiled files keep getting refreshed
 * across the rename instead of being mistaken for hand-written ones.
 */
const GENERATED_MARKERS = ['GENERATED by clankervault', 'GENERATED by vault'];

/** true when the start of a file's content carries any marker that makes it ours to overwrite */
export function isGenerated(headContent: string): boolean {
  return GENERATED_MARKERS.some((m) => headContent.includes(m));
}

/**
 * Appended to FILE outputs only (never to MCP get_context responses): the file
 * channel is guaranteed to reach the model, so it is the right place to teach
 * the model that the voluntary MCP channel exists.
 */
export const MCP_HINT =
  'Memory: this file is a compiled view of the user\'s vault. ' +
  'If a clankervault MCP server is connected, call get_context at the start of the conversation for fresher context, ' +
  'and save new durable knowledge with the remember tool.';

/** shared section layout for markdown-based targets */
export function renderMarkdownBody(ctx: CompiledContext): string {
  const parts: string[] = [];
  parts.push(ctx.project.facts);
  if (ctx.state) parts.push(`## State (work in progress)\n\n${ctx.state}`);
  const taste = [...ctx.globalTaste, ...ctx.records.taste];
  if (taste.length) parts.push(`## Taste & style\n\n${taste.join('\n')}`);
  if (ctx.records.recipe.length) parts.push(`## Recipes (how things are done here)\n\n${ctx.records.recipe.join('\n')}`);
  if (ctx.records.decision.length) parts.push(`## Decisions\n\n${ctx.records.decision.join('\n')}`);
  if (ctx.records.fact.length) parts.push(`## Facts\n\n${ctx.records.fact.join('\n')}`);
  if (ctx.unconfirmed.length) parts.push(`## Recent (unconfirmed, take with a grain of salt)\n\n${ctx.unconfirmed.join('\n')}`);
  if (ctx.profile) parts.push(`## About the user\n\n${ctx.profile}`);
  if (ctx.droppedCount > 0) parts.push(`<!-- ${ctx.droppedCount} records omitted by token budget; full detail lives in the vault -->`);
  return parts.join('\n\n') + '\n';
}
