import type { Adapter } from './index.js';
import { MCP_HINT, renderMarkdownBody } from './index.js';

// .windsurfrules is plain text; markdown reads fine there, but use a text header
export const windsurf: Adapter = {
  name: 'windsurf',
  filename: '.windsurfrules',
  render: (ctx) => `# GENERATED by clankervault - do not edit. Regenerate with \`clanker compile\`.\n\n${renderMarkdownBody(ctx)}\n${MCP_HINT}\n`,
};
